### ISSUE TITLE
Is it possible to pass the can level?

### ISSUE THREAD

**Issue by aydinugur** [alexejrotar/fungus#2]
https://github.com/alexejrotar/fungus/blob/844d9918771ecf14ed77c7a3a1c01c48b0f9dcc4/data/levelCollection.js#L99
Hi, I really enjoyed your game. Great stuff! But I am really curious that is it possible to pass the can level? I mean I have tried the all possibilities but cannot pass this level. Thanks!

**Comment by alexejrotar** [comment]
Hi, glad to hear you liked my game and actually played it till the end :) and no, it is not possible, it is meant as a joke and I tried to hint at it in the intro text. Thanks for playing :)

**Comment by aydinugur** [comment]
Brilliant levels and theme though, thanks for your answer (:
